# finance-chart/values.yaml

global:
  namespace: default
  domain: ammm.website

frontend:
  image: aungmyinmyintmyat/finance-frontend:latest
  containerPort: 8080
  servicePort: 80

backend:
  image: aungmyinmyintmyat/finance-backend:latest
  containerPort: 8080
  servicePort: 5000

mysql:
  image: mysql:8.0
  port: 3306
  database: finance_db
  pvcSize: 1Gi