apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finance-secrets
              key: db-password
        - name: DB_NAME
          value: "finance_db"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: finance-secrets
              key: jwt-secret