apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finance-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.global.domain }}
  rules:
    - host: {{ .Values.global.domain | default "ammm.website" }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: {{ .Values.backend.servicePort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ .Values.frontend.servicePort }}