apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-app
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.containerPort }}
  selector:
    app: frontend